# Generated by Django 4.2.5 on 2023-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='born',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
