# Generated by Django 4.2.5 on 2023-09-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_author_born'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='date_of_publication',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='author',
            name='born',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
